final _hostIdPattern = RegExp(r'^ehost-[0-9a-f]{20}$');

/// User-facing naming policy for a Host identity.
///
/// The six-character marker is only a nearby-device presentation aid. Trust
/// continues to come from the signed Host endpoint and the stored public key.
String hostMarker(String hostId) {
  if (!_hostIdPattern.hasMatch(hostId)) {
    throw FormatException('Invalid Eidolon Host ID: $hostId');
  }
  return hostId.substring(hostId.length - 6);
}

String defaultHostDisplayName(String hostId) => 'Eidolon-${hostMarker(hostId)}';

/// Normalizes names generated by the pre-v1 naming policy without changing a
/// user-provided name.
String normalizeHostDisplayName(String hostId, String displayName) {
  final canonicalName = defaultHostDisplayName(hostId);
  final legacyGeneratedName = 'Eidolon ${hostId.substring(6, 12)}';
  return displayName == legacyGeneratedName ? canonicalName : displayName;
}
